# See https://developers.cloudflare.com/workers/wrangler/configuration/ for more configuration options
#:schema node_modules/wrangler/config-schema.json
name = "optimizely-edge-delivery-dc"
main = "src/index.ts"
compatibility_date = "2024-10-08"
compatibility_flags = ["nodejs_compat"]

# ED: For CF logging
[observability]
enabled = true

[vars]
SNIPPET_ID = "28411280946"
DEV_URL = "https://demonchronicles.com/"

# ED: still had to create the route manually in CF
routes = [
  { pattern = "demonchronicles.com/*", zone_name = "demonchronicles.com" }
]
